name: java checkstyle

on:
  pull_request:
    paths:
      - ".github/workflows/checkstyle.yml" # this file
      - "**/*.java" # all java files
  push:
    paths:
      - "**/*.java" # all java files
  schedule:
    - cron: "*/5 * * * *"


    

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: checkout # checksout repo
        uses: actions/checkout@v2
        
      - name: checkstyle
        uses: dbelyaev/action-checkstyle@master # github repo of linter being used
        with:
          checkstyle_version: 9.0.1
          github_token: ${{ secrets.github_token }} # authorises
          reporter: github-check # reports with github checks on pulls and commits
          level: warning # will displays warnings (code style, ect.) & erros (symantics)
          paths:
            "**/*.java"
          # Uses google coding conventions (incl javadocs)
